### ISSUE TITLE
Fix highlighter color in dark mode

### ISSUE THREAD

**Issue by cassidoo** [cassidoo/cardstock#2]
Right now the yellow on white highlight color is not cute nor accessible, gotta fix this across light and dark mode.

**Comment by NeffCodes** [comment]
When you refer to cute, do you mean you would like a different color or a tint/shade of yellow that corresponded with each theme?

**Comment by cassidoo** [comment]
Hahaha sorry for the lack of clarity @NeffCodes, I wasn't expecting many folks to see this 😆 

So right now, when you highlight text by itself, it looks like this:
![image](https://user-images.githubusercontent.com/1454517/170374925-c32cef18-0da0-4be1-bae7-3f9fb62f24b3.png)

But when you have a highlighted section using Obsidian highlights , it looks like this:
![image](https://user-images.githubusercontent.com/1454517/170375270-c7c11af2-25e5-43d9-8814-67c5988c224b.png)

This looks good in light mode, but in dark mode it looks like this:
![image](https://user-images.githubusercontent.com/1454517/170375241-bc3948dc-2051-422b-8cb9-b39b3c7c98af.png)

**Comment by NeffCodes** [comment]
No problem! Do you mind if I take a look at it? I took the liberty of quickly looking up some color contrast ratios, but since I don't know the full scope of what you want to achieve, what level do you want the accessibility ratio to be?  

For example, color yellow #756b13 would provide a fairly strong contrast against the [text](https://color.a11y.com/ContrastPair/?bgcolor=756b13&fgcolor=ffffff), but not against the [background](https://color.a11y.com/ContrastPair/?bgcolor=2f2a27&fgcolor=ffffff). 

However, based on the contrast between your red color and the white text in dark mode, you could go lighter to have a similar ratio with [yellow #877B16](https://color.a11y.com/ContrastPair/?bgcolor=756b13&fgcolor=ffffff) to stand out more against the background. Or, if you would rather have a different color, you go with a [blue #4779c5](https://color.a11y.com/ContrastPair/?bgcolor=756b13&fgcolor=ffffff).

**Comment by cassidoo** [comment]
Hey @NeffCodes that #756b13 looks great! I think it's okay if the text has the strongest contrast, I think that's most important. I appreciate you looking at this, thank you!

**Comment by NeffCodes** [comment]
No problem, happy to help!
